### ISSUE TITLE
adding Ignore URL feature

### ISSUE THREAD

**Issue by mamadou-diallo** [eunbeek/findBrokenGlass#11]
The following shall be met : 
The --ignore, -i, \i flag is optional, and if present should take a filepath and use it to load and parse an ignored URLs text file. If the ignore file isn't found, give an appropriate error message. Otherwise, all URLs should be checked against this list to see if they need to be ignored.

Here are some example ignore files.

First, a file with only a comment is valid:

/1. Empty file, nothing will be ignored
Second, a file with multiple comments and a URL is valid:

/ 2. File with a comment and single URL that matches any URL
/that starts with https://www.google.com, for example:

 /https://www.google.com/index.html would match
 /https://www.google.com/ would match
/ https://www.google.ca would NOT match
https://www.google.com
Third, a file that has no comments and only URLs is valid:

https://www.google.com
Fourth, a file with anything other than a comment (#) or URL (http://, https://) is invalid:

/ This is invalid.  It doesn't use http:// or https://
www.google.com
If the file isn't valid, give an appropriate error message and exit. Otherwise, use the file's URL patterns to test all the URLs being processed, skipping any that match.

**Comment by eunbeek** [comment]
Sounds really good. Thank you so much for your contribution.

**Comment by eunbeek** [comment]
This issue is closed by #12
